<?php
/**
 * NoFrixionMoneyMoovModelsRule
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoFrixion MoneyMoov API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nofrixion\Client\Model;

use \ArrayAccess;
use \Nofrixion\Client\ObjectSerializer;

/**
 * NoFrixionMoneyMoovModelsRule Class Doc Comment
 *
 * @category Class
 * @package  Nofrixion\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NoFrixionMoneyMoovModelsRule implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NoFrixion.MoneyMoov.Models.Rule';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'account_id' => 'string',
        'merchant_id' => 'string',
        'user_id' => 'string',
        'approver_id' => 'string',
        'name' => 'string',
        'description' => 'string',
        'is_disabled' => 'bool',
        'status' => 'string',
        'trigger_on_pay_in' => 'bool',
        'trigger_cron_expression' => 'string',
        'time_zone_id' => 'string',
        'start_at' => '\DateTime',
        'end_at' => '\DateTime',
        'sweep_action' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsSweepAction',
        'approve_url' => 'string',
        'on_approved_web_hook_url' => 'string',
        'on_execution_error_web_hook_url' => 'string',
        'on_execution_success_web_hook_url' => 'string',
        'web_hook_secret' => 'string',
        'inserted' => '\DateTime',
        'last_updated' => '\DateTime',
        'last_executed_at' => '\DateTime',
        'last_run_at_transaction_date' => '\DateTime',
        'created_by' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsUser',
        'authorised_by' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsUser',
        'account' => '\Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentAccount'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'account_id' => 'uuid',
        'merchant_id' => 'uuid',
        'user_id' => 'uuid',
        'approver_id' => 'uuid',
        'name' => null,
        'description' => null,
        'is_disabled' => null,
        'status' => null,
        'trigger_on_pay_in' => null,
        'trigger_cron_expression' => null,
        'time_zone_id' => null,
        'start_at' => 'date-time',
        'end_at' => 'date-time',
        'sweep_action' => null,
        'approve_url' => null,
        'on_approved_web_hook_url' => null,
        'on_execution_error_web_hook_url' => null,
        'on_execution_success_web_hook_url' => null,
        'web_hook_secret' => null,
        'inserted' => 'date-time',
        'last_updated' => 'date-time',
        'last_executed_at' => 'date-time',
        'last_run_at_transaction_date' => 'date-time',
        'created_by' => null,
        'authorised_by' => null,
        'account' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'account_id' => false,
        'merchant_id' => false,
        'user_id' => true,
        'approver_id' => true,
        'name' => true,
        'description' => true,
        'is_disabled' => false,
        'status' => false,
        'trigger_on_pay_in' => false,
        'trigger_cron_expression' => true,
        'time_zone_id' => true,
        'start_at' => true,
        'end_at' => true,
        'sweep_action' => false,
        'approve_url' => true,
        'on_approved_web_hook_url' => true,
        'on_execution_error_web_hook_url' => true,
        'on_execution_success_web_hook_url' => true,
        'web_hook_secret' => true,
        'inserted' => false,
        'last_updated' => false,
        'last_executed_at' => true,
        'last_run_at_transaction_date' => false,
        'created_by' => false,
        'authorised_by' => false,
        'account' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'account_id' => 'accountID',
        'merchant_id' => 'merchantID',
        'user_id' => 'userID',
        'approver_id' => 'approverID',
        'name' => 'name',
        'description' => 'description',
        'is_disabled' => 'isDisabled',
        'status' => 'status',
        'trigger_on_pay_in' => 'triggerOnPayIn',
        'trigger_cron_expression' => 'triggerCronExpression',
        'time_zone_id' => 'timeZoneId',
        'start_at' => 'startAt',
        'end_at' => 'endAt',
        'sweep_action' => 'sweepAction',
        'approve_url' => 'approveUrl',
        'on_approved_web_hook_url' => 'onApprovedWebHookUrl',
        'on_execution_error_web_hook_url' => 'onExecutionErrorWebHookUrl',
        'on_execution_success_web_hook_url' => 'onExecutionSuccessWebHookUrl',
        'web_hook_secret' => 'webHookSecret',
        'inserted' => 'inserted',
        'last_updated' => 'lastUpdated',
        'last_executed_at' => 'lastExecutedAt',
        'last_run_at_transaction_date' => 'lastRunAtTransactionDate',
        'created_by' => 'createdBy',
        'authorised_by' => 'authorisedBy',
        'account' => 'account'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'account_id' => 'setAccountId',
        'merchant_id' => 'setMerchantId',
        'user_id' => 'setUserId',
        'approver_id' => 'setApproverId',
        'name' => 'setName',
        'description' => 'setDescription',
        'is_disabled' => 'setIsDisabled',
        'status' => 'setStatus',
        'trigger_on_pay_in' => 'setTriggerOnPayIn',
        'trigger_cron_expression' => 'setTriggerCronExpression',
        'time_zone_id' => 'setTimeZoneId',
        'start_at' => 'setStartAt',
        'end_at' => 'setEndAt',
        'sweep_action' => 'setSweepAction',
        'approve_url' => 'setApproveUrl',
        'on_approved_web_hook_url' => 'setOnApprovedWebHookUrl',
        'on_execution_error_web_hook_url' => 'setOnExecutionErrorWebHookUrl',
        'on_execution_success_web_hook_url' => 'setOnExecutionSuccessWebHookUrl',
        'web_hook_secret' => 'setWebHookSecret',
        'inserted' => 'setInserted',
        'last_updated' => 'setLastUpdated',
        'last_executed_at' => 'setLastExecutedAt',
        'last_run_at_transaction_date' => 'setLastRunAtTransactionDate',
        'created_by' => 'setCreatedBy',
        'authorised_by' => 'setAuthorisedBy',
        'account' => 'setAccount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'account_id' => 'getAccountId',
        'merchant_id' => 'getMerchantId',
        'user_id' => 'getUserId',
        'approver_id' => 'getApproverId',
        'name' => 'getName',
        'description' => 'getDescription',
        'is_disabled' => 'getIsDisabled',
        'status' => 'getStatus',
        'trigger_on_pay_in' => 'getTriggerOnPayIn',
        'trigger_cron_expression' => 'getTriggerCronExpression',
        'time_zone_id' => 'getTimeZoneId',
        'start_at' => 'getStartAt',
        'end_at' => 'getEndAt',
        'sweep_action' => 'getSweepAction',
        'approve_url' => 'getApproveUrl',
        'on_approved_web_hook_url' => 'getOnApprovedWebHookUrl',
        'on_execution_error_web_hook_url' => 'getOnExecutionErrorWebHookUrl',
        'on_execution_success_web_hook_url' => 'getOnExecutionSuccessWebHookUrl',
        'web_hook_secret' => 'getWebHookSecret',
        'inserted' => 'getInserted',
        'last_updated' => 'getLastUpdated',
        'last_executed_at' => 'getLastExecutedAt',
        'last_run_at_transaction_date' => 'getLastRunAtTransactionDate',
        'created_by' => 'getCreatedBy',
        'authorised_by' => 'getAuthorisedBy',
        'account' => 'getAccount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_PENDING_APPROVAL = 'PendingApproval';
    public const STATUS_ACTIVE = 'Active';
    public const STATUS_DISABLED = 'Disabled';
    public const STATUS_FAILED = 'Failed';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_PENDING_APPROVAL,
            self::STATUS_ACTIVE,
            self::STATUS_DISABLED,
            self::STATUS_FAILED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('merchant_id', $data ?? [], null);
        $this->setIfExists('user_id', $data ?? [], null);
        $this->setIfExists('approver_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('is_disabled', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('trigger_on_pay_in', $data ?? [], null);
        $this->setIfExists('trigger_cron_expression', $data ?? [], null);
        $this->setIfExists('time_zone_id', $data ?? [], null);
        $this->setIfExists('start_at', $data ?? [], null);
        $this->setIfExists('end_at', $data ?? [], null);
        $this->setIfExists('sweep_action', $data ?? [], null);
        $this->setIfExists('approve_url', $data ?? [], null);
        $this->setIfExists('on_approved_web_hook_url', $data ?? [], null);
        $this->setIfExists('on_execution_error_web_hook_url', $data ?? [], null);
        $this->setIfExists('on_execution_success_web_hook_url', $data ?? [], null);
        $this->setIfExists('web_hook_secret', $data ?? [], null);
        $this->setIfExists('inserted', $data ?? [], null);
        $this->setIfExists('last_updated', $data ?? [], null);
        $this->setIfExists('last_executed_at', $data ?? [], null);
        $this->setIfExists('last_run_at_transaction_date', $data ?? [], null);
        $this->setIfExists('created_by', $data ?? [], null);
        $this->setIfExists('authorised_by', $data ?? [], null);
        $this->setIfExists('account', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets account_id
     *
     * @return string|null
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string|null $account_id account_id
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        if (is_null($account_id)) {
            throw new \InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets merchant_id
     *
     * @return string|null
     */
    public function getMerchantId()
    {
        return $this->container['merchant_id'];
    }

    /**
     * Sets merchant_id
     *
     * @param string|null $merchant_id The ID of the merchant that owns the account.
     *
     * @return self
     */
    public function setMerchantId($merchant_id)
    {
        if (is_null($merchant_id)) {
            throw new \InvalidArgumentException('non-nullable merchant_id cannot be null');
        }
        $this->container['merchant_id'] = $merchant_id;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string|null $user_id user_id
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        if (is_null($user_id)) {
            array_push($this->openAPINullablesSetToNull, 'user_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets approver_id
     *
     * @return string|null
     */
    public function getApproverId()
    {
        return $this->container['approver_id'];
    }

    /**
     * Sets approver_id
     *
     * @param string|null $approver_id approver_id
     *
     * @return self
     */
    public function setApproverId($approver_id)
    {
        if (is_null($approver_id)) {
            array_push($this->openAPINullablesSetToNull, 'approver_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('approver_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['approver_id'] = $approver_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets is_disabled
     *
     * @return bool|null
     */
    public function getIsDisabled()
    {
        return $this->container['is_disabled'];
    }

    /**
     * Sets is_disabled
     *
     * @param bool|null $is_disabled is_disabled
     *
     * @return self
     */
    public function setIsDisabled($is_disabled)
    {
        if (is_null($is_disabled)) {
            throw new \InvalidArgumentException('non-nullable is_disabled cannot be null');
        }
        $this->container['is_disabled'] = $is_disabled;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets trigger_on_pay_in
     *
     * @return bool|null
     */
    public function getTriggerOnPayIn()
    {
        return $this->container['trigger_on_pay_in'];
    }

    /**
     * Sets trigger_on_pay_in
     *
     * @param bool|null $trigger_on_pay_in trigger_on_pay_in
     *
     * @return self
     */
    public function setTriggerOnPayIn($trigger_on_pay_in)
    {
        if (is_null($trigger_on_pay_in)) {
            throw new \InvalidArgumentException('non-nullable trigger_on_pay_in cannot be null');
        }
        $this->container['trigger_on_pay_in'] = $trigger_on_pay_in;

        return $this;
    }

    /**
     * Gets trigger_cron_expression
     *
     * @return string|null
     */
    public function getTriggerCronExpression()
    {
        return $this->container['trigger_cron_expression'];
    }

    /**
     * Sets trigger_cron_expression
     *
     * @param string|null $trigger_cron_expression trigger_cron_expression
     *
     * @return self
     */
    public function setTriggerCronExpression($trigger_cron_expression)
    {
        if (is_null($trigger_cron_expression)) {
            array_push($this->openAPINullablesSetToNull, 'trigger_cron_expression');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('trigger_cron_expression', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['trigger_cron_expression'] = $trigger_cron_expression;

        return $this;
    }

    /**
     * Gets time_zone_id
     *
     * @return string|null
     */
    public function getTimeZoneId()
    {
        return $this->container['time_zone_id'];
    }

    /**
     * Sets time_zone_id
     *
     * @param string|null $time_zone_id time_zone_id
     *
     * @return self
     */
    public function setTimeZoneId($time_zone_id)
    {
        if (is_null($time_zone_id)) {
            array_push($this->openAPINullablesSetToNull, 'time_zone_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('time_zone_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['time_zone_id'] = $time_zone_id;

        return $this;
    }

    /**
     * Gets start_at
     *
     * @return \DateTime|null
     */
    public function getStartAt()
    {
        return $this->container['start_at'];
    }

    /**
     * Sets start_at
     *
     * @param \DateTime|null $start_at start_at
     *
     * @return self
     */
    public function setStartAt($start_at)
    {
        if (is_null($start_at)) {
            array_push($this->openAPINullablesSetToNull, 'start_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('start_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['start_at'] = $start_at;

        return $this;
    }

    /**
     * Gets end_at
     *
     * @return \DateTime|null
     */
    public function getEndAt()
    {
        return $this->container['end_at'];
    }

    /**
     * Sets end_at
     *
     * @param \DateTime|null $end_at end_at
     *
     * @return self
     */
    public function setEndAt($end_at)
    {
        if (is_null($end_at)) {
            array_push($this->openAPINullablesSetToNull, 'end_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['end_at'] = $end_at;

        return $this;
    }

    /**
     * Gets sweep_action
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsSweepAction|null
     */
    public function getSweepAction()
    {
        return $this->container['sweep_action'];
    }

    /**
     * Sets sweep_action
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsSweepAction|null $sweep_action sweep_action
     *
     * @return self
     */
    public function setSweepAction($sweep_action)
    {
        if (is_null($sweep_action)) {
            throw new \InvalidArgumentException('non-nullable sweep_action cannot be null');
        }
        $this->container['sweep_action'] = $sweep_action;

        return $this;
    }

    /**
     * Gets approve_url
     *
     * @return string|null
     */
    public function getApproveUrl()
    {
        return $this->container['approve_url'];
    }

    /**
     * Sets approve_url
     *
     * @param string|null $approve_url If set this property holds the URL an approver needs to visit in order to  complete a strong authentication check in order to approve the rule.
     *
     * @return self
     */
    public function setApproveUrl($approve_url)
    {
        if (is_null($approve_url)) {
            array_push($this->openAPINullablesSetToNull, 'approve_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('approve_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['approve_url'] = $approve_url;

        return $this;
    }

    /**
     * Gets on_approved_web_hook_url
     *
     * @return string|null
     */
    public function getOnApprovedWebHookUrl()
    {
        return $this->container['on_approved_web_hook_url'];
    }

    /**
     * Sets on_approved_web_hook_url
     *
     * @param string|null $on_approved_web_hook_url Optional URL to receive an HTTP request with the rule details when the rule status changes to   approved. The webhook payload will contain the full Rule object.
     *
     * @return self
     */
    public function setOnApprovedWebHookUrl($on_approved_web_hook_url)
    {
        if (is_null($on_approved_web_hook_url)) {
            array_push($this->openAPINullablesSetToNull, 'on_approved_web_hook_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('on_approved_web_hook_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['on_approved_web_hook_url'] = $on_approved_web_hook_url;

        return $this;
    }

    /**
     * Gets on_execution_error_web_hook_url
     *
     * @return string|null
     */
    public function getOnExecutionErrorWebHookUrl()
    {
        return $this->container['on_execution_error_web_hook_url'];
    }

    /**
     * Sets on_execution_error_web_hook_url
     *
     * @param string|null $on_execution_error_web_hook_url Optional URL to receive an HTTP request when a rule execution attempt fails. The webhook   payload will contain a Problem object.
     *
     * @return self
     */
    public function setOnExecutionErrorWebHookUrl($on_execution_error_web_hook_url)
    {
        if (is_null($on_execution_error_web_hook_url)) {
            array_push($this->openAPINullablesSetToNull, 'on_execution_error_web_hook_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('on_execution_error_web_hook_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['on_execution_error_web_hook_url'] = $on_execution_error_web_hook_url;

        return $this;
    }

    /**
     * Gets on_execution_success_web_hook_url
     *
     * @return string|null
     */
    public function getOnExecutionSuccessWebHookUrl()
    {
        return $this->container['on_execution_success_web_hook_url'];
    }

    /**
     * Sets on_execution_success_web_hook_url
     *
     * @param string|null $on_execution_success_web_hook_url Optional URL to receive an HTTP request when a rule execution attempt succeeds. The webhook   payload will contain a list of any payouts that were submitted for the rule execution.
     *
     * @return self
     */
    public function setOnExecutionSuccessWebHookUrl($on_execution_success_web_hook_url)
    {
        if (is_null($on_execution_success_web_hook_url)) {
            array_push($this->openAPINullablesSetToNull, 'on_execution_success_web_hook_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('on_execution_success_web_hook_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['on_execution_success_web_hook_url'] = $on_execution_success_web_hook_url;

        return $this;
    }

    /**
     * Gets web_hook_secret
     *
     * @return string|null
     */
    public function getWebHookSecret()
    {
        return $this->container['web_hook_secret'];
    }

    /**
     * Sets web_hook_secret
     *
     * @param string|null $web_hook_secret If set this secret will be used to sign Web Hook requests.
     *
     * @return self
     */
    public function setWebHookSecret($web_hook_secret)
    {
        if (is_null($web_hook_secret)) {
            array_push($this->openAPINullablesSetToNull, 'web_hook_secret');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('web_hook_secret', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['web_hook_secret'] = $web_hook_secret;

        return $this;
    }

    /**
     * Gets inserted
     *
     * @return \DateTime|null
     */
    public function getInserted()
    {
        return $this->container['inserted'];
    }

    /**
     * Sets inserted
     *
     * @param \DateTime|null $inserted inserted
     *
     * @return self
     */
    public function setInserted($inserted)
    {
        if (is_null($inserted)) {
            throw new \InvalidArgumentException('non-nullable inserted cannot be null');
        }
        $this->container['inserted'] = $inserted;

        return $this;
    }

    /**
     * Gets last_updated
     *
     * @return \DateTime|null
     */
    public function getLastUpdated()
    {
        return $this->container['last_updated'];
    }

    /**
     * Sets last_updated
     *
     * @param \DateTime|null $last_updated last_updated
     *
     * @return self
     */
    public function setLastUpdated($last_updated)
    {
        if (is_null($last_updated)) {
            throw new \InvalidArgumentException('non-nullable last_updated cannot be null');
        }
        $this->container['last_updated'] = $last_updated;

        return $this;
    }

    /**
     * Gets last_executed_at
     *
     * @return \DateTime|null
     */
    public function getLastExecutedAt()
    {
        return $this->container['last_executed_at'];
    }

    /**
     * Sets last_executed_at
     *
     * @param \DateTime|null $last_executed_at last_executed_at
     *
     * @return self
     */
    public function setLastExecutedAt($last_executed_at)
    {
        if (is_null($last_executed_at)) {
            array_push($this->openAPINullablesSetToNull, 'last_executed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_executed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_executed_at'] = $last_executed_at;

        return $this;
    }

    /**
     * Gets last_run_at_transaction_date
     *
     * @return \DateTime|null
     */
    public function getLastRunAtTransactionDate()
    {
        return $this->container['last_run_at_transaction_date'];
    }

    /**
     * Sets last_run_at_transaction_date
     *
     * @param \DateTime|null $last_run_at_transaction_date The most recent transaction date when the rule was last run.
     *
     * @return self
     */
    public function setLastRunAtTransactionDate($last_run_at_transaction_date)
    {
        if (is_null($last_run_at_transaction_date)) {
            throw new \InvalidArgumentException('non-nullable last_run_at_transaction_date cannot be null');
        }
        $this->container['last_run_at_transaction_date'] = $last_run_at_transaction_date;

        return $this;
    }

    /**
     * Gets created_by
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsUser|null
     */
    public function getCreatedBy()
    {
        return $this->container['created_by'];
    }

    /**
     * Sets created_by
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsUser|null $created_by created_by
     *
     * @return self
     */
    public function setCreatedBy($created_by)
    {
        if (is_null($created_by)) {
            throw new \InvalidArgumentException('non-nullable created_by cannot be null');
        }
        $this->container['created_by'] = $created_by;

        return $this;
    }

    /**
     * Gets authorised_by
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsUser|null
     */
    public function getAuthorisedBy()
    {
        return $this->container['authorised_by'];
    }

    /**
     * Sets authorised_by
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsUser|null $authorised_by authorised_by
     *
     * @return self
     */
    public function setAuthorisedBy($authorised_by)
    {
        if (is_null($authorised_by)) {
            throw new \InvalidArgumentException('non-nullable authorised_by cannot be null');
        }
        $this->container['authorised_by'] = $authorised_by;

        return $this;
    }

    /**
     * Gets account
     *
     * @return \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentAccount|null
     */
    public function getAccount()
    {
        return $this->container['account'];
    }

    /**
     * Sets account
     *
     * @param \Nofrixion\Client\Model\NoFrixionMoneyMoovModelsPaymentAccount|null $account account
     *
     * @return self
     */
    public function setAccount($account)
    {
        if (is_null($account)) {
            throw new \InvalidArgumentException('non-nullable account cannot be null');
        }
        $this->container['account'] = $account;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


